import { Category, FileTypeFilter, ProductItem, Review } from './types';

export const categories: Category[] = [
  { slug: 'business', name: 'شركات ورواد أعمال', nameEn: 'Business', icon: '🏢', description: 'ملفات وقوالب مخصصة للشركات، العقود، والأتمتة.' },
  { slug: 'accounting', name: 'محاسبين وماليين', nameEn: 'Accounting', icon: '📊', description: 'أدوات مالية، شيتات إكسل، وداشبورد Power BI متقدمة.' },
  { slug: 'engineering', name: 'مهندسين ومعماريين', nameEn: 'Engineering', icon: '📐', description: 'مخططات، بلوكات AutoCAD، عائلات Revit، وجداول حصر.' },
  { slug: 'students', name: 'طلاب وباحثين', nameEn: 'Students', icon: '🎓', description: 'سير ذاتية ATS، قوالب Notion، وعروض تخرج أكاديمية.' },
  { slug: 'individuals', name: 'أفراد وإنتاجية', nameEn: 'Individuals', icon: '👤', description: 'ميزانية شخصية، تخطيط حياة، وعقود عمل حر.' }
];

export const fileTypeFilters: FileTypeFilter[] = [
  { slug: 'excel', name: 'شيتات Excel', icon: '📗' },
  { slug: 'notion', name: 'قوالب Notion', icon: '📝' },
  { slug: 'powerpoint', name: 'سلايدات PowerPoint', icon: '📊' },
  { slug: 'word-pdf', name: 'عقود PDF/Word', icon: '📄' },
  { slug: 'canva', name: 'قوالب Canva', icon: '🎨' },
  { slug: 'cad-revit', name: 'AutoCAD/Revit', icon: '📐' },
  { slug: 'ai-prompts', name: 'برومبتات AI', icon: '🤖' }
];

export interface BundleDeal {
  id: string;
  title: string;
  description: string;
  discountBadge: string;
  originalPrice: number;
  bundlePrice: number;
  productIds: string[];
  imageUrl: string;
  category: string;
}

export const bundleDeals: BundleDeal[] = [
  {
    id: 'bundle-biz',
    title: 'حقيبة تأسيس الشركات ورواد الأعمال المتكاملة',
    description: 'تشمل: حزمة العقود القانونية + قالب عرض المستثمرين (Pitch Deck) + دراسة جدوى ونموذج مالي لـ 3 سنوات.',
    discountBadge: 'وفر 35%',
    originalPrice: 750,
    bundlePrice: 485,
    productIds: ['p1', 'p2', 'p3'],
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    category: 'business'
  },
  {
    id: 'bundle-acc',
    title: 'ترسانة المحاسب المالي والمدير التنفيذي',
    description: 'تشمل: شيت المحاسبة الشاملة + لوحة Power BI المالية + نظام إدارة المخازن وتكلفة المبيعات.',
    discountBadge: 'وفر 40%',
    originalPrice: 920,
    bundlePrice: 550,
    productIds: ['p7', 'p8', 'p10'],
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    category: 'accounting'
  },
  {
    id: 'bundle-eng',
    title: 'باقة المهندس التنفيذي والمعماري الشاملة',
    description: 'تشمل: مكتبة 1500+ بلوك AutoCAD + شيت الحسابات الإنشائية + قوالب مقايسات حصر الكميات BOQ.',
    discountBadge: 'وفر 30%',
    originalPrice: 760,
    bundlePrice: 530,
    productIds: ['p13', 'p14', 'p15'],
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    category: 'engineering'
  }
];

export const products: ProductItem[] = [
  // ================= 1. BUSINESS (6 Products) =================
  {
    id: 'p1',
    title: 'حزمة عقود العمل والـ NDA واتفاقيات الشراكة القانونية',
    description: 'حزمة شاملة من العقود القانونية المصاغة بعناية وفق القوانين المعمول بها بمصر والخليج. تشمل عقود توظيف، شراكة، وعدم إفشاء قابلة للتعديل الفوري.',
    price: 250,
    originalPrice: 400,
    category: 'business',
    fileType: 'word-pdf',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 65,
    salesCount: 420,
    vendorName: 'مكتب الصفوة القانوني',
    tags: ['عقود', 'قانوني', 'شركات', 'شراكة', 'توظيف'],
    createdAt: new Date().toISOString(),
    featured: true,
    technicalSpecs: {
      compatibility: ['Microsoft Word 2016 - 2024', 'Google Docs', 'Adobe Acrobat Pro'],
      fileFormats: ['.DOCX', '.PDF (A4 Print Ready 300 DPI)'],
      pagesCount: 28,
      jurisdiction: 'القانون المدني والتجاري المصري والأنظمة السعودية ونظام المعاملات الإماراتي',
    },
  },
  {
    id: 'p2',
    title: 'قالب عرض المستثمرين وجولات التمويل (Pitch Deck Pro)',
    description: 'عرض تقديمي مصمم خصيصاً لجولات الاستثمار وعرض الأفكار التجارية على المستثمرين وحاضنات الأعمال باحترافية عالية مع 30 شريحة قابلة للتخصيص.',
    price: 180,
    category: 'business',
    fileType: 'powerpoint',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 94,
    salesCount: 580,
    vendorName: 'رواد التصميم',
    tags: ['عروض', 'مستثمرين', 'بوربوينت', 'شركات ناشئة'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p3',
    title: 'دراسة جدوى ونموذج مالي لـ 3 سنوات للشركات الناشئة',
    description: 'شيت إكسل متقدم ونموذج وورد لدراسة الجدوى وحساب نقطة التعادل، مصادر الإيرادات، وتوقعات الربحية لمدة 3 سنوات مع الرسوم البيانية.',
    price: 320,
    originalPrice: 500,
    category: 'business',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 38,
    salesCount: 210,
    vendorName: 'استشارات فينتشر',
    tags: ['دراسة جدوى', 'نموذج مالي', 'إكسل', 'استثمار'],
    createdAt: new Date().toISOString(),
    featured: true,
    technicalSpecs: {
      compatibility: ['Excel 2016 - 2024', 'Microsoft 365', 'Google Sheets'],
      fileFormats: ['.XLSX', '.XLSM'],
      sheetsCount: 6,
      formulasCount: 940,
    },
  },
  {
    id: 'p4',
    title: 'سيناريوهات أتمتة Make / Zapier لخدمة العملاء والفواتير',
    description: 'مخططات أتمتة جاهزة (Blueprints) لربط المتجر بالواتساب، إرسال الفواتير تلقائياً للعميل، وتحديث بيانات المبيعات في Google Sheets.',
    price: 220,
    category: 'business',
    fileType: 'ai-prompts',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 42,
    salesCount: 195,
    vendorName: 'أوتوميشن هاب',
    tags: ['أتمتة', 'Zapier', 'Make', 'واتساب', 'فواتير'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p5',
    title: 'نظام إدارة علاقات العملاء والمبيعات (Notion CRM Pro)',
    description: 'قالب نوشن تفاعلي للشركات الصغيرة لتتبع مسار الصفقات، بيانات العملاء، ومواعيد المتابعة مع خط أنابيب مبيعات بصري جذاب.',
    price: 190,
    category: 'business',
    fileType: 'notion',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 56,
    salesCount: 310,
    vendorName: 'نوشن بزنس',
    tags: ['CRM', 'Notion', 'مبيعات', 'إدارة عملاء'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p6',
    title: 'حزمة سياسات ولوائح الموارد البشرية والتوظيف (HR Pack)',
    description: 'أكثر من 15 وثيقة ولوائح عمل داخلية: سياسة العمل عن بعد، الإجازات، تقييم الأداء السنوي، وقوالب خطابات العروض الوظيفية (Job Offer).',
    price: 240,
    originalPrice: 380,
    category: 'business',
    fileType: 'word-pdf',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 29,
    salesCount: 160,
    vendorName: 'خبراء الموارد البشرية',
    tags: ['HR', 'توظيف', 'لوائح', 'عروض وظيفية'],
    createdAt: new Date().toISOString()
  },

  // ================= 2. ACCOUNTING (6 Products) =================
  {
    id: 'p7',
    title: 'شيت إكسل المحاسبة الشاملة وميزان المراجعة والقيود',
    description: 'نظام محاسبي متكامل ومؤتمت على الإكسل. يتيح تتبع الإيرادات، المصروفات، وإصدار ميزان المراجعة والقوائم المالية الختامية بنقرة زر.',
    price: 350,
    originalPrice: 500,
    category: 'accounting',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 145,
    salesCount: 980,
    vendorName: 'الحلول المالية الذكية',
    tags: ['محاسبة', 'إكسل', 'تقارير مالية', 'قيود يومية'],
    createdAt: new Date().toISOString(),
    featured: true,
    technicalSpecs: {
      compatibility: ['Excel 2016 - 2026', 'Microsoft 365', 'Google Sheets'],
      fileFormats: ['.XLSX', '.XLSM (VBA Macros Enabled)'],
      sheetsCount: 12,
      formulasCount: 1850,
    },
  },
  {
    id: 'p8',
    title: 'نظام إدارة المخازن وتكلفة البضاعة المباعة (FIFO / LIFO)',
    description: 'شيت إكسل احترافي لتتبع رصيد المخزن، كروت الصنف، تنبيهات حد الطلب الأدنى، واحتساب تكلفة البضاعة المباعة تلقائياً.',
    price: 280,
    category: 'accounting',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 78,
    salesCount: 460,
    vendorName: 'لوجستكس إكسل',
    tags: ['مخازن', 'تكلفة', 'FIFO', 'إكسل', 'جرد'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p9',
    title: 'حاسبة الضرائب والإقرار الإلكتروني لضريبة القيمة المضافة',
    description: 'أداة حساب ضريبة القيمة المضافة لمصر (14%)، السعودية (15%)، والإمارات (5%) مع تجهيز بيانات الإقرار الضريبي وتفصيل المبيعات والمشتريات.',
    price: 150,
    category: 'accounting',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 52,
    salesCount: 340,
    vendorName: 'أحمد المالي',
    tags: ['ضرائب', 'VAT', 'إقرار ضريبي', 'إكسل'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p10',
    title: 'لوحة Power BI التفاعلية للمؤشرات والتحليل المالي',
    description: 'داشبورد متقدمة على Power BI تتيح تحويل الأرقام الصامتة إلى رسوم بيانية حية ومؤشرات أداء مالية تفاعلية لاتخاذ القرارات الاستراتيجية.',
    price: 290,
    originalPrice: 450,
    category: 'accounting',
    fileType: 'powerpoint',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 68,
    salesCount: 380,
    vendorName: 'داتا برو',
    tags: ['Power BI', 'داشبورد', 'تحليل مالي', 'مؤشرات'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p11',
    title: 'شيت مسير الرواتب وحساب التأمينات وضريبة كسب العمل 2026',
    description: 'شيت مؤتمت لحساب صافي الرواتب والاستقطاعات والتأمينات والبدلات طبقاً لآخر تعديلات القوانين الضريبية المصرية مع كشوف مرتبات جاهزة للطباعة.',
    price: 170,
    category: 'accounting',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 88,
    salesCount: 530,
    vendorName: 'باي رول بلس',
    tags: ['رواتب', 'ضرائب', 'تأمينات', 'كسب العمل'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p12',
    title: 'نموذج توقعات التدفق النقدي والسيولة (Cash Flow Forecast)',
    description: 'أداة تنبؤ مالي دقيقة لاكتشاف فجوات السيولة النقدية قبل حدوثها وضبط التدفقات الداخلة والخارجة لضمان استقرار المشروعات.',
    price: 200,
    category: 'accounting',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 34,
    salesCount: 220,
    vendorName: 'فاينانشال موديلز',
    tags: ['تدفق نقدي', 'سيولة', 'توقعات', 'إكسل'],
    createdAt: new Date().toISOString()
  },

  // ================= 3. ENGINEERING (6 Products) =================
  {
    id: 'p13',
    title: 'مكتبة بلوكات AutoCAD المعمارية المعتمدة (1500+ بلوك)',
    description: 'أكثر من 1500 بلوك أوتوكاد معتمد للأثاث، الأبواب، النوافذ، والواجهات المعمارية المنسقة بأعلى مقاييس الرسم الهندسي وطبقات الألوان.',
    price: 200,
    originalPrice: 350,
    category: 'engineering',
    fileType: 'cad-revit',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 110,
    salesCount: 720,
    vendorName: 'أركيتيكت هاب',
    tags: ['AutoCAD', 'معماري', 'بلوكات', 'تصميم'],
    createdAt: new Date().toISOString(),
    featured: true,
    technicalSpecs: {
      compatibility: ['AutoCAD 2013 - 2026', 'Autodesk Revit 2020 - 2026', 'Civil 3D'],
      fileFormats: ['.DWG', '.DXF', '.PAT'],
      blocksCount: 1520,
      lodStandard: 'LOD 350 (BIM Compliant)',
    },
  },
  {
    id: 'p14',
    title: 'شيت الحسابات وتصميم العناصر الإنشائية والخرسانة المسلحة',
    description: 'شيت إكسل لتصميم وحساب قطاعات الأعمدة، الكمرات، والأساسات الخرسانية وفق الأكواد الهندسية الحديثة، مع حساب كميات حديد التسليح.',
    price: 300,
    category: 'engineering',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f7?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 65,
    salesCount: 390,
    vendorName: 'م. إبراهيم الإنشائي',
    tags: ['إنشائي', 'خرسانة', 'تسليح', 'تصميم هندسي'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p15',
    title: 'قوالب مقايسات وحساب كميات البناء والتشطيبات (BOQ)',
    description: 'شيت متقدم لحصر كميات الخرسانة، الحديد، البياض، السيراميك، والدهانات مع تسعير بنود المقاولة وجداول مستخلصات المقاولين.',
    price: 260,
    category: 'engineering',
    fileType: 'excel',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 82,
    salesCount: 480,
    vendorName: 'كونتراكتور برو',
    tags: ['حصر كميات', 'BOQ', 'مقايسات', 'تشطيبات'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p16',
    title: 'عائلات Revit جاهزة للتصميم الداخلي وشبكات MEP',
    description: 'مجموعة عائلات ريفيت بارامترية (Parametric Families) للمفروشات والإضاءة ومخارج التكييف والصحي جاهزة للرندرة وخرائط الـ BIM.',
    price: 240,
    category: 'engineering',
    fileType: 'cad-revit',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 39,
    salesCount: 230,
    vendorName: 'بيم أركي تك',
    tags: ['Revit', 'BIM', 'عائلات', 'ديكور', 'MEP'],
    createdAt: new Date().toISOString(),
    technicalSpecs: {
      compatibility: ['Autodesk Revit 2020 - 2026', 'Navisworks', 'AutoCAD Architecture'],
      fileFormats: ['.RFA (Revit Parametric Family)', '.RVT'],
      blocksCount: 450,
      lodStandard: 'LOD 350',
    },
  },
  {
    id: 'p17',
    title: 'جدول زمني لإدارة المشروعات مع منحنى S-Curve ومستخلصات',
    description: 'نموذج إكسل متكامل لتخطيط المشروعات الهندسية، رسم مخطط جانت (Gantt Chart)، ورصد منحنى التدفق المالي التراكمي ونسب الإنجاز.',
    price: 190,
    category: 'engineering',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 47,
    salesCount: 290,
    vendorName: 'بروجكتس بلانر',
    tags: ['إدارة مشاريع', 'Gantt', 'S-Curve', 'جدول زمني'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p18',
    title: 'شيت حساب أحمال التكييف والتهوية وتوزيع مجاري الهواء (HVAC)',
    description: 'شيت متطور لحساب أطنان التبريد المطلوبة للمساحات السكنية والتجارية، حساب مقاسات مجاري الصاج (Ducts)، واختيار مخارج الهواء.',
    price: 220,
    category: 'engineering',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 31,
    salesCount: 180,
    vendorName: 'ميكانيكا ستوديو',
    tags: ['HVAC', 'تكييف', 'أحمال حرارية', 'دكت'],
    createdAt: new Date().toISOString()
  },

  // ================= 4. STUDENTS (6 Products) =================
  {
    id: 'p19',
    title: 'حزمة السير الذاتية الحديثة المتوافقة مع أنظمة الـ ATS',
    description: '10 نماذج سيرة ذاتية عصرية ومصممة بدقة لتجتاز روبوتات الفرز الآلي (ATS) وتضمن وصول طلبك لمسؤولي التوظيف مباشرة بصيغتي Word و PDF.',
    price: 79,
    originalPrice: 150,
    category: 'students',
    fileType: 'word-pdf',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 340,
    salesCount: 2150,
    vendorName: 'كارير استوديو',
    tags: ['سيرة ذاتية', 'توظيف', 'ATS', 'خريجين'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p20',
    title: 'نظام إدارة الحياة الجامعية والأبحاث في Notion',
    description: 'نظام إدارة دراسي متكامل داخل Notion: تتبع المحاضرات، مراجع الأبحاث، مواعيد التسليم، ومخطط مراجعة الامتحانات الذكي.',
    price: 99,
    category: 'students',
    fileType: 'notion',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 195,
    salesCount: 1040,
    vendorName: 'أكاديميا نوشن',
    tags: ['Notion', 'دراسة', 'تنظيم', 'أبحاث'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p21',
    title: 'حزمة قوالب عروض التخرج والمشاريع العلمية (PowerPoint)',
    description: 'سلايدات بوربوينت احترافية لعرض مشاريع التخرج ورسائل الماجستير مع مخططات وجداول إحصائية ورسوم توضيحية تسهل الشرح أمام لجان التحكيم.',
    price: 110,
    category: 'students',
    fileType: 'powerpoint',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 82,
    salesCount: 460,
    vendorName: 'برزنتيشن كيدز',
    tags: ['تخرج', 'مناقشة', 'بوربوينت', 'أبحاث'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p22',
    title: 'دليل برومبتات الذكاء الاصطناعي للأبحاث الأكاديمية والترجمة',
    description: 'أكثر من 100 برومبت دقيق لصياغة الاستفسارات البحثية، تلخيص المقالات العلمية، إعادة الصياغة الأكاديمية، والتحقق من المراجع دون أخطاء.',
    price: 85,
    category: 'students',
    fileType: 'ai-prompts',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 76,
    salesCount: 510,
    vendorName: 'برومبت برو',
    tags: ['ذكاء اصطناعي', 'برومبت', 'ChatGPT', 'بحث علمي'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p23',
    title: 'مخطط التحضير لاختبارات الآيلتس واللغات (IELTS / TOEFL)',
    description: 'خطة دراسية مجدولة داخل Notion مع بنك المفردات الأكثر تكراراً، قوالب كتابة Task 1 و Task 2، وحاسبة تقريبية لنقاط الـ Band Score.',
    price: 75,
    category: 'students',
    fileType: 'notion',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 63,
    salesCount: 390,
    vendorName: 'إنجلش ماستر',
    tags: ['IELTS', 'لغات', 'دراسة', 'اختبارات'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p24',
    title: 'قالب كتابة ورقة بحثية بمعايير IEEE و APA العالمية',
    description: 'قوالب جاهزة بصيغتي Word و LaTeX منسقة بنمط العمودين، الهوامش القياسية، جداول الرسوم، وترقيم المراجع التلقائي وفق أحدث المعايير الأكاديمية.',
    price: 65,
    category: 'students',
    fileType: 'word-pdf',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 41,
    salesCount: 260,
    vendorName: 'أكاديميك رايتر',
    tags: ['IEEE', 'APA', 'أبحاث', 'LaTeX', 'Word'],
    createdAt: new Date().toISOString()
  },

  // ================= 5. INDIVIDUALS & PRODUCTIVITY (6 Products) =================
  {
    id: 'p25',
    title: 'مخطط الميزانية والمصاريف الشخصية الذكي بقاعدة 50/30/20',
    description: 'شيت إكسل تلقائي يوضح أين يذهب راتبك شهرياً، مع توزيع النفقات بقاعدة 50/30/20 الذكية ورسوم بيانية تحفيزية لخطط الادخار.',
    price: 110,
    originalPrice: 200,
    category: 'individuals',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 230,
    salesCount: 1220,
    vendorName: 'مدخر محترف',
    tags: ['ميزانية', 'مصاريف', 'إكسل', 'توفير', 'ادخار'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p26',
    title: 'لوحة تخطيط الحياة السنوية وبناء العادات (Notion Dashboard)',
    description: 'لوحة تحكم تفاعلية متكاملة لتتبع أهداف العام، تنظيم القراءة، قياس مؤشرات العادات اليومية، ومراجعة الإنجازات الأسبوعية.',
    price: 120,
    category: 'individuals',
    fileType: 'notion',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 140,
    salesCount: 890,
    vendorName: 'لايف ديزاينر',
    tags: ['Notion', 'أهداف', 'عادات', 'إنتاجية'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p27',
    title: 'حزمة قوالب وبوستات السوشيال ميديا التسويقية (Canva / PPT)',
    description: 'أكثر من 80 تصميماً عصرياً لمنشورات وقصص انستغرام وفيسبوك قابلة للتعديل بضغطة زر لنشر محتوى جذاب وزيادة المتابعين لمشروعك.',
    price: 160,
    category: 'individuals',
    fileType: 'powerpoint',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviewCount: 98,
    salesCount: 490,
    vendorName: 'كرييتف ستوديو',
    tags: ['سوشيال ميديا', 'تصميم', 'تسويق', 'انستغرام'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p28',
    title: 'مخطط الوجبات الأسبوعي وقائمة التسوق الصحية الذكية',
    description: 'شيت إكسل ونوشن لتنظيم جدول الطبخ الأسبوعي، حساب السعرات والمصروفات، وتوليد قائمة مشتريات السوبرماركت لتفادي الهدر المالي.',
    price: 60,
    category: 'individuals',
    fileType: 'excel',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 54,
    salesCount: 310,
    vendorName: 'هيلثي لايف',
    tags: ['وجبات', 'توفير', 'صحة', 'تسوق'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p29',
    title: 'حزمة عقود العمل الحر وحماية مستحقات الفريلانسر',
    description: 'صيغ عقود واضحة وموثوقة للمستقلين (تصميم، برمجة، كتابة، تسويق) تضمن حقوقك المالية، شروط التعديلات، وجدول دفع المستحقات لتفادي النزاعات.',
    price: 140,
    originalPrice: 220,
    category: 'individuals',
    fileType: 'word-pdf',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 112,
    salesCount: 670,
    vendorName: 'فريلانسر شيلد',
    tags: ['عمل حر', 'فريلانس', 'عقود', 'حقوق مالية'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p30',
    title: 'مكتبة برومبتات Midjourney للتصميم التجاري والموك آب',
    description: 'أكثر من 150 برومبت معتمد لتوليد صور منتجات واقعية، خلفيات ثلاثية الأبعاد، وتصاميم تغليف إبداعية جاهزة للحملات الإعلانية.',
    price: 95,
    category: 'individuals',
    fileType: 'ai-prompts',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1686191128892-3b37813f0799?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 89,
    salesCount: 530,
    vendorName: 'أي آي ديزاينرز',
    tags: ['Midjourney', 'ذكاء اصطناعي', 'موك آب', 'إعلانات'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'p31',
    title: 'حزمة 60 قالب بوست وريلز Canva احترافي لشركات التجارة والمطاعم',
    description: 'مجموعة قوالب كانفا مصممة بأبعاد 1080×1080 و 1080×1920 جاهزة للتعديل بضغطة زر. تشمل إعلانات خصومات، عروض نهاية الموسم، ومسابقات تفاعلية.',
    price: 199,
    originalPrice: 350,
    category: 'individuals',
    fileType: 'canva',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 78,
    salesCount: 410,
    vendorName: 'كرييتف كانفا ستوديو',
    tags: ['canva', 'انستجرام', 'ريلز', 'سوشيال ميديا', 'تصاميم', 'تسويق'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p32',
    title: 'قالب السيرة الذاتية التنفيذي الذهبي ATS + رابط تعديل فوري في Canva',
    description: 'قالب سيرة ذاتية ثنائي اللغة (عربي / إنجليزي) مصمم لاجتياز فلاتر ATS مع رابط فتح وتعديل مباشر في Canva وخيارات ألوان متعددة.',
    price: 89,
    originalPrice: 160,
    category: 'students',
    fileType: 'canva',
    license: 'personal',
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    rating: 5.0,
    reviewCount: 145,
    salesCount: 920,
    vendorName: 'مسارك المهني',
    tags: ['canva', 'سيرة ذاتية', 'ATS', 'توظيف', 'لينكدإن'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p33',
    title: 'نظام الفواتير وعروض الأسعار الضريبية للشركات والمستقلين (Canva & Excel Master)',
    description: 'قوالب فواتير أنيقة ومتوافقة مع متطلبات هيئة الزكاة والضريبة والجمارك ومصلحة الضرائب المصرية، مع QR code وحساب تلقائي للضريبة.',
    price: 149,
    originalPrice: 250,
    category: 'accounting',
    fileType: 'canva',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 63,
    salesCount: 380,
    vendorName: 'فواتير تك',
    tags: ['canva', 'فواتير', 'ضرائب', 'حسابات', 'عروض أسعار'],
    createdAt: new Date().toISOString(),
    featured: false
  },
  {
    id: 'p34',
    title: 'حزمة قوالب العروض التقديمية والتقارير السنوية الفاخرة للشركات (Canva Pitch Deck)',
    description: 'أكثر من 55 شريحة عرض تقديمية بتنسيق 16:9 لعرض الميزانيات، خطط العمل، والنتائج السنوية بأعلى معايير الإخراج البصري.',
    price: 240,
    originalPrice: 420,
    category: 'business',
    fileType: 'canva',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 51,
    salesCount: 290,
    vendorName: 'سلايد برو',
    tags: ['canva', 'سلايدات', 'تقارير', 'عرض تقديمي', 'شركات'],
    createdAt: new Date().toISOString(),
    featured: true
  },
  {
    id: 'p35',
    title: 'مجموعة شهادات التقدير والاعتماد الأكاديمي والمهني (Vector & Canva Ready)',
    description: '12 قالباً لشهادات التخرج، التدريب، والتكريم الرسمي بنقوش إسلامية وزخارف كلاسيكية حديثة قابلة للتعديل والطباعة الفورية بدقة 300 DPI.',
    price: 110,
    originalPrice: 200,
    category: 'students',
    fileType: 'canva',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 42,
    salesCount: 215,
    vendorName: 'أكاديمي ديزاين',
    tags: ['canva', 'شهادات', 'تدريب', 'اعتماد', 'تعليم'],
    createdAt: new Date().toISOString(),
    featured: false
  },
  {
    id: 'p36',
    title: 'حزمة عقود الشراكة وحماية الملكية الفكرية وصيغ التفويض التجاري (Word + Canva Sign)',
    description: 'صيغ تعاقدية قانونية متقدمة لتوزيع الأرباح، تأسيس الشركات، وحفظ حقوق الملكية الفكرية وتراخيص الاستخدام التجاري للبرمجيات.',
    price: 280,
    originalPrice: 450,
    category: 'business',
    fileType: 'word-pdf',
    license: 'commercial',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 37,
    salesCount: 175,
    vendorName: 'دار العدالة للاستشارات',
    tags: ['canva', 'عقود', 'شراكة', 'ملكية فكرية', 'قانوني'],
    createdAt: new Date().toISOString(),
    featured: false
  }
];

export const reviews: Review[] = [
  { id: 'r1', productId: 'p1', userName: 'أحمد علي (محامي ومؤسس)', rating: 5, comment: 'عقود ممتازة ومصاغة بدقة قانونية عالية وفرت علي آلاف الجنيهات.', date: '2026-09-15' },
  { id: 'r2', productId: 'p1', userName: 'محمد حسن (صاحب شركة)', rating: 5, comment: 'شاملة وجيدة، يسهل تخصيصها وتعديلها في برنامج Word.', date: '2026-09-20' },
  { id: 'r3', productId: 'p2', userName: 'سارة خالد (رائدة أعمال)', rating: 5, comment: 'التصميم مبهر جداً وساعدنا في تقديم عرضنا أمام المستثمرين بنجاح!', date: '2026-09-10' },
  { id: 'r4', productId: 'p7', userName: 'كريم محمود (محاسب قانوني)', rating: 5, comment: 'أفضل شيت إكسل محاسبي جربته، المعادلات دقيقة وميزان المراجعة متزن.', date: '2026-09-25' },
  { id: 'r5', productId: 'p7', userName: 'نورهان سعيد (مديرة مالية)', rating: 5, comment: 'سهل الاستخدام ومنظم جداً، التقارير الختامية ممتازة.', date: '2026-09-28' },
  { id: 'r6', productId: 'p13', userName: 'م. طارق (مهندس استشاري)', rating: 5, comment: 'البلوكات نظيفة جداً وخفيفة على ملفات الأوتوكاد بدون أي بطء.', date: '2026-09-22' },
  { id: 'r7', productId: 'p19', userName: 'عمر فاروق (خريج هندسة)', rating: 5, comment: 'بفضل القالب تم قبولي في مقابلتين عمل خلال أسبوع واحد!', date: '2026-09-26' },
  { id: 'r8', productId: 'p20', userName: 'محمود سامي (طالب جامعي)', rating: 5, comment: 'قالب نوشن غير حياتي الدراسية بالكامل ورتب وقتي.', date: '2026-09-29' },
  { id: 'r9', productId: 'p29', userName: 'ياسمين عبد الله (مصممة مستقلة)', rating: 5, comment: 'عقود الفريلانس أنقذت مستحقاتي مع عميل مماطل، أنصح بها بشدة.', date: '2026-09-30' }
];

export const mockProducts = products;
export const mockReviews = reviews;
export const mockCategories = categories;
